name: Deploy Debian Stable
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy-debian-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: tachimawari_interfaces

      - name: Add stable Debian repository and rosdep sources list
        run: |
          sudo apt update && sudo apt install curl
          curl -s ${{ secrets.SERVER_BASE_URL }}/debian/setup.bash | bash -s
          curl -s ${{ secrets.SERVER_BASE_URL }}/rosdep/setup.bash | bash -s

      - name: Build stable Debian package
        uses: ichiro-its/ros2-build-debian-action@main
        with:
          ros2-distro: rolling

      - name: Deploy stable Debian package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "package/*.deb"
          target: "~/temp/stable/tachimawari_interfaces/"
          rm: true

      - name: Prepare stable Debian package in the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ${{ secrets.SERVER_REPO_DIR }}/debian
            reprepro includedeb stable ~/temp/stable/tachimawari_interfaces/package/*.deb
            rm -rf ~/temp/stable/tachimawari_interfaces/
